[phases.setup]
nixPkgs = ["python311"]

[phases.build]
cmds = ["python3.11 -m pip install -r backend/requirements.txt"]

[start]
cmd = "cd backend && gunicorn api_server:app --bind 0.0.0.0:$PORT --timeout 300 --worker-class gevent"
